inherit_from: .rubocop_todo.yml

require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-seo-tag.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*
