inherit_from: .rubocop_todo.yml

require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-seo-tag.gemspec

Layout/BlockLength:
  Exclude:
    - spec/**/*
