language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.6

before_install:
  - gem update --system
  - gem install bundler

script: script/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION="~> 3.3"
    - JEKYLL_VERSION=">= 4.0.0.pre.alpha1"
